services:
  - type: web
    name: node-socket-io
    env: docker
    plan: free
    region: ohio
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 7272
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: aura-db # Replace if necessary
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false
